## Rules

<!-- BEGIN f4d-kit:rules (generated by scripts/render_instructions.py — do not edit inside) -->
_Rules index — generated from the rule-module frontmatter. Do not edit between these markers; run `render_instructions.py --write`._

**Always applies (every task):**
- `core` — Core
- `guards` — Guards, Not Memos
- `response-format` — Response format
- `silent-degradation` — Silent Degradation

**Load the file when working in the area:**
- `api` — API
- `blockchain` — Blockchain
- `capability-parity` — Capability Parity
- `contracts` — Contracts (multi-repo)
- `data-integration` — Data Integration
- `database` — Database
- `dataprotection` — Data Protection
- `design-a11y` — Design accessibility
- `design-components` — Design components
- `design-handoff` — Design handoff
- `design-tokens` — Design tokens
- `determinism` — Determinism & Content Addressing
- `keysafety` — Key Safety
- `livesystem` — Live System
- `money` — Money
- `observability` — Observability
- `python` — Python
- `statelessness` — Statelessness
- `storage` — Object Storage
- `typescript` — TypeScript
- `webhooks` — Webhooks
<!-- END f4d-kit:rules -->
