#!/usr/bin/env python3
"""
Instruction-file sync (spec 001, capability 2) — the rule modules are the single
source; the per-tool instruction files (CLAUDE.md, AGENTS.md, GEMINI.md,
.cursor/rules/*.mdc) hold a *rendered* index of them inside a delimited managed
block. Rendering is deterministic, so drift between the modules and any tool's
file is detectable and fixable, and no instruction file becomes a second source
of truth (A2).

Each rule module carries YAML-ish frontmatter:

    ---
    id: api
    always_apply: false
    ---
    # API

`id` is stable and unique; `always_apply` marks the org floor surfaced on every
task. `.claude/rules/REGISTRY.md` (rendered on demand) and `.claude/rules/org.md`
(the per-repo org-profile constraints block, written verbatim by /project-init
with no frontmatter) are NOT rule modules and are skipped.

Usage:
  render_instructions.py --rules-dir .claude/rules --write
  render_instructions.py --rules-dir .claude/rules --check      # exit 2 on drift
  render_instructions.py --rules-dir templates/rules --validate # structure only

Fail-loud by doctrine (G-03): missing/duplicate `id`, a non-boolean
`always_apply`, an unreadable module, or (in --check) a target with no managed
block OR more than one managed block is an ERROR (exit 2), never a silent pass.
"""
import argparse
import os
import re
import sys

BEGIN = "<!-- BEGIN f4d-kit:rules (generated by scripts/render_instructions.py — do not edit inside) -->"
END = "<!-- END f4d-kit:rules -->"
BLOCK_RE = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
TOKEN = "{{RULES_INDEX}}"
NOT_MODULES = {"REGISTRY.md", "org.md"}  # rendered/verbatim files, never rule modules
DEFAULT_TARGETS = ["CLAUDE.md", "AGENTS.md", ".cursor/rules/f4d-kit.mdc"]


def die(msg):
    print(f"render_instructions: ERROR: {msg}", file=sys.stderr)
    sys.exit(2)


def parse_module(path):
    try:
        text = open(path, encoding="utf-8").read()
    except OSError as e:
        die(f"cannot read module {path}: {e}")
    if not text.startswith("---\n"):
        die(f"{path}: no frontmatter — every rule module needs `id` and `always_apply` "
            f"(if this is not a rule module, it must be named in NOT_MODULES)")
    end = text.find("\n---\n", 4)
    if end == -1:
        die(f"{path}: frontmatter opened with --- but never closed")
    fm, body = text[4:end], text[end + 5:]
    meta = {}
    for line in fm.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            die(f"{path}: frontmatter line is not `key: value`: {line!r}")
        k, v = line.split(":", 1)
        meta[k.strip()] = v.strip()
    if "id" not in meta or not meta["id"]:
        die(f"{path}: frontmatter missing `id`")
    if "always_apply" not in meta:
        die(f"{path}: frontmatter missing `always_apply`")
    if meta["always_apply"] not in ("true", "false"):
        die(f"{path}: `always_apply` must be true or false, got {meta['always_apply']!r}")
    title = None
    for line in body.splitlines():
        if line.startswith("# "):
            title = line[2:].strip()
            break
    if not title:
        die(f"{path}: no `# Title` heading after the frontmatter")
    return meta["id"], meta["always_apply"] == "true", title


def collect(rules_dir):
    if not os.path.isdir(rules_dir):
        die(f"rules dir not found: {rules_dir}")
    mods = []
    for name in sorted(os.listdir(rules_dir)):
        if not name.endswith(".md") or name in NOT_MODULES:
            continue
        mid, always, title = parse_module(os.path.join(rules_dir, name))
        mods.append((mid, always, title))
    if not mods:
        die(f"no rule modules in {rules_dir} — nothing to render")
    ids = [m[0] for m in mods]
    dup = sorted({i for i in ids if ids.count(i) > 1})
    if dup:
        die(f"duplicate module id(s): {dup} — ids must be unique across modules")
    return mods


def render_block(mods):
    always = sorted([m for m in mods if m[1]], key=lambda m: m[0])
    ondemand = sorted([m for m in mods if not m[1]], key=lambda m: m[0])
    lines = [BEGIN,
             "_Rules index — generated from the rule-module frontmatter. "
             "Do not edit between these markers; run `render_instructions.py --write`._",
             "",
             "**Always applies (every task):**"]
    lines += [f"- `{mid}` — {title}" for mid, _, title in always] or ["- _(none)_"]
    lines += ["", "**Load the file when working in the area:**"]
    lines += [f"- `{mid}` — {title}" for mid, _, title in ondemand] or ["- _(none)_"]
    lines.append(END)
    return "\n".join(lines)


def apply_to(text, block):
    """Insert or replace the managed block; collapse duplicates to exactly one."""
    if TOKEN in text:
        # scaffold path: CLAUDE.md.tmpl carries {{RULES_INDEX}} for the block.
        return text.replace(TOKEN, block)
    if BLOCK_RE.search(text):
        # Replace the FIRST managed block with the fresh render; drop any others
        # (a bad merge can leave two — collapse rather than leave duplicates).
        first = [True]

        def repl(_m):
            if first[0]:
                first[0] = False
                return block
            return ""
        return BLOCK_RE.sub(repl, text)
    sep = "" if text == "" else ("\n" if text.endswith("\n") else "\n\n")
    head = "" if text == "" else sep
    return text + head + ("## Rules\n\n" if "## Rules" not in text else "") + block + "\n"


def block_status(text, block):
    """Return None if in sync, else a human reason string."""
    matches = BLOCK_RE.findall(text)
    if TOKEN in text:
        return "unrendered {{RULES_INDEX}} token — run --write"
    if not matches:
        return "no managed block — run --write"
    if len(matches) > 1:
        return f"{len(matches)} managed blocks — run --write to normalize to one"
    if matches[0] != block:
        return "managed block is stale — run --write"
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rules-dir", default=".claude/rules")
    ap.add_argument("--root", default=".", help="repo root the targets are relative to")
    ap.add_argument("--targets", default=",".join(DEFAULT_TARGETS),
                    help="comma-separated instruction files to render")
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--validate", action="store_true", help="frontmatter structure only")
    args = ap.parse_args()

    mods = collect(args.rules_dir)  # fail-loud on any structural problem
    if args.validate:
        print(f"render_instructions: OK — {len(mods)} module(s), frontmatter valid.")
        return
    block = render_block(mods)
    targets = [t.strip() for t in args.targets.split(",") if t.strip()]

    if args.check:
        drift = []
        for t in targets:
            p = os.path.join(args.root, t)
            if not os.path.exists(p):
                drift.append(f"{t}: missing (no rendered instruction file)")
                continue
            reason = block_status(open(p, encoding="utf-8").read(), block)
            if reason:
                drift.append(f"{t}: {reason}")
        if drift:
            print("render_instructions: DRIFT — instruction files disagree with the rule modules:",
                  file=sys.stderr)
            for d in drift:
                print(f"  - {d}", file=sys.stderr)
            sys.exit(2)
        print(f"render_instructions: OK — {len(targets)} instruction file(s) in sync.")
        return

    if args.write:
        for t in targets:
            p = os.path.join(args.root, t)
            os.makedirs(os.path.dirname(p) or ".", exist_ok=True)
            text = open(p, encoding="utf-8").read() if os.path.exists(p) else ""
            open(p, "w", encoding="utf-8").write(apply_to(text, block))
        print(f"render_instructions: wrote managed block into {len(targets)} file(s).")
        return

    ap.error("one of --write, --check, --validate is required")


if __name__ == "__main__":
    main()
